mqtt:
  username: '#<enter the username for the mqtt broker>'
  password: '#<enter the password for the mqtt broker>'

graphdb:
  username: '#<enter the username for the graph database>'
  password: '#<enter the password for the graph database>'  
