mqtt:
  broker_url: 'mqtt://198.168.220.3:1883'
  topic : "#"
  qos: 1
  keep_alive: 60
  dynaconf_merge: true


graphdb:
  url: 'bolt://localhost:7687'
  database: ''
  node_types: ["ENTERPRISE", "FACILITY", "AREA", "LINE", "DEVICE"]
  dynaconf_merge: true
   